name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 1

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cargo build
        id: build
        run: cargo build --all-features

      - name: cargo test
        id: test
        run: cargo test --all-features

      - name: rustfmt
        id: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --workspace --all-features --tests -- -D warnings

  test-windows:
    needs: [test-linux]
    if: needs.test-linux.result == 'success'
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cargo build
        id: build
        run: cargo build --all-features

      - name: cargo test
        run: cargo test --all-features

  test-osx:
    needs: [test-linux]
    if: needs.test-linux.result == 'success'
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cargo build
        id: build
        run: cargo build --all-features

      - name: cargo test
        run: cargo test --all-features
