name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            lint: 1

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: rustup update

      - name: cargo check
        run: cargo check

      - name: cargo build
        run: cargo build

      - name: cargo test
        run: cargo test

      - name: rustfmt
        if: github.event_name == 'pull_request' && matrix.lint
        run: cargo fmt --all -- --check

      - name: clippy
        if: github.event_name == 'pull_request' && matrix.lint
        run: cargo clippy --tests -- -D warnings
